// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student.DAL.Data.Context;

#nullable disable

namespace Student.DAL.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20240320124834_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Student.DAL.Data.Models.StudentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IQLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 27,
                            Department = 1,
                            Email = "Mustafa@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Mustafa",
                            lName = "Abdo"
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            Department = 4,
                            Email = "Ahmed@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Ahmed",
                            lName = "Ali"
                        },
                        new
                        {
                            Id = 3,
                            Age = 30,
                            Department = 0,
                            Email = "Sara@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Sara",
                            lName = "Mohamed"
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            Department = 2,
                            Email = "Fatima@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Fatima",
                            lName = "Hassan"
                        },
                        new
                        {
                            Id = 5,
                            Age = 26,
                            Department = 3,
                            Email = "Khaled@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Khaled",
                            lName = "Ahmed"
                        },
                        new
                        {
                            Id = 6,
                            Age = 29,
                            Department = 1,
                            Email = "Laila@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Laila",
                            lName = "Omar"
                        },
                        new
                        {
                            Id = 7,
                            Age = 24,
                            Department = 1,
                            Email = "Youssef@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Youssef",
                            lName = "Kareem"
                        },
                        new
                        {
                            Id = 8,
                            Age = 31,
                            Department = 0,
                            Email = "Nour@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Nour",
                            lName = "Ahmed"
                        },
                        new
                        {
                            Id = 9,
                            Age = 27,
                            Department = 3,
                            Email = "Ali@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Ali",
                            lName = "Sara"
                        },
                        new
                        {
                            Id = 10,
                            Age = 32,
                            Department = 2,
                            Email = "Hala@gmail.com",
                            IQLevel = "Super intelligent",
                            fName = "Hala",
                            lName = "Mohamed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
